name: pot-bot
services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    env_file:
      - .env
    environment:
      - WSR_ENABLE=true
      - WS_URLS=["ws://pot:8080/onebot/v11/ws"]
      - NAPCAT_UID=1000
      - NAPCAT_GID=1000
    volumes:
      - ./napcat/config:/app/napcat/config
      - ./napcat/data:/app/.config/QQ
      - ./napcat/logs:/app/napcat/logs
    ports:
      - 6099:6099
    restart: always
    depends_on:
      pot:
        condition: service_healthy
        restart: true

  pot:
    # image: ghcr.io/pkuoriginalfire/pot-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pot
    env_file:
      - .env
    volumes:
      - ./pot:/app/data
    restart: always
