name: pot-bot
services:
  napcat:
    environment:
      - ACCOUNT=${ACCOUNT}
      - WSR_ENABLE=true
      - WS_URLS=["ws://pot:8080/onebot/v11/ws"]
      - NAPCAT_UID=1000
      - NAPCAT_GID=1000
    container_name: napcat
    volumes:
      - ./napcat/config:/app/napcat/config
      - ./napcat/data:/app/.config/QQ
      - ./napcat/logs:/app/napcat/logs
    ports:
      - 6099:6099
    restart: always
    image: mlikiowa/napcat-docker:latest

  pot:
    volumes:
      - ./pot:/app/data
    image: ghcr.io/pkuoriginalfire/pot-bot:latest
